name: pixify transformer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create .env file
        run: echo "PORT=${PORT}" > .env
        env:
          PORT: ${{secrets.PORT}}
      - name: Install dependencies
        run: go mod tidy
      - name: Build go binary
        run: go build -o pixify-transformer
      - name: Run go binary
        run: |
          sudo systemctl daemon-reload
          sudo systemctl stop pixify.service
          sudo systemctl restart pixify.service
          sudo systemctl status pixify.service --no-pager
